name: Build Meteoric Kernel (inline-2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: inline-2
          submodules: recursive

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential curl flex gcc clang git zip unzip libssl-dev libncurses-dev python3 wget jq

      - name: Clone Neutron Clang
        run: |
          mkdir -p ~/meteoric/neutron-clang
          cd ~/meteoric/neutron-clang
          curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
          chmod a+x antman
          ./antman -S
          cd -
          echo "$HOME/meteoric/neutron-clang/bin" >> $GITHUB_PATH

      - name: Export environment variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=Neoteric" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=HELLBOY017" >> $GITHUB_ENV
          echo "PROCS=$(nproc --all)" >> $GITHUB_ENV
          echo "DISTRO=$(source /etc/os-release && echo "$NAME")" >> $GITHUB_ENV
          echo "KBUILD_COMPILER_STRING=$($HOME/meteoric/neutron-clang/bin/clang --version | head -n 1 | sed -E 's/\(http.*\)//g')" >> $GITHUB_ENV

      - name: Enable KernelSU-Next
        run: |
          git submodule update --init --recursive KernelSU-Next
          git submodule update --init --recursive susfs4ksu
          sed -i "s/-Meteoric/-Meteoric-$(cat Version)-KSU-Next/" arch/arm64/configs/vendor/meteoric_defconfig

      - name: Clean build
        run: |
          make O=out clean && make O=out mrproper

      - name: Build kernel
        run: |
          make O=out ARCH=arm64 vendor/meteoric_defconfig
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            LLVM=1 \
            LLVM_IAS=1 \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_COMPAT=arm-linux-androideabi- \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip

      - name: Package with AnyKernel3
        run: |
          IMAGE=out/arch/arm64/boot/Image
          DTBO=out/arch/arm64/boot/dtbo.img
          DTB=out/arch/arm64/boot/dtb
          cp $IMAGE $DTBO $DTB anykernel/
          cd anykernel
          FINAL_ZIP="Meteoric-$(cat ../Version)-KSU-Next-$(date +%y%m%d-%H%M).zip"
          zip -r9 "../out/$FINAL_ZIP" * -x README
          cd ..

      - name: Upload zip to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(cat Version)
          files: out/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
